### ISSUE TITLE
The slf4j logging module

### ISSUE THREAD

**Issue by e-jajaga** [protegeproject/swrltab#2]
Can I build the swrltab-${version}-jar-with-dependencies.jar without the slf4j module? Is it mandatory for applications using swrltab API? If it's not, then how can I remove all slf4j bindings in the pom file? 
I tried to remove slf4j manually, but I am receiving now the following exception:
SLF4J: Detected both jcl-over-slf4j.jar AND slf4j-jcl.jar on the class path, preempting StackOverflowError.

**Comment by martinjoconnor** [comment]
I cleaned up the POM and removed this (unneeded) dependency.
